### ISSUE TITLE
The code is for 32 or 64?

### ISSUE THREAD

**Issue by hackdorte** [thebitradio/Bitradio#5]
I want to start compiling. Please is 32 or 64bit?

**Comment by BANKICO** [comment]
64bit

2017-09-28 21:09 GMT+08:00 hackdorte <notifications@github.com>:

**Comment by jamilservicos** [comment]
I would not answer this question, since of course it is for both, however this type of application works best on 64bits, for it is clear that 64 bits is the recommended for multi cores.

This is a non compiled source, so it is adaptive to 32 or 64 bits, determined by the compiler and / or system used.

But if you use 2 or more cores, it is highly recommended to use 64bit system, so you can use full processor processing.


If your question has resolved, please close the issue!

**Comment by hackdorte** [comment]
I just can not compile for 32 bits and all dependencies are satisfied. Sorry for the inconvenience and the question. No further. Thanks.
